export const types = {}
types.SET_USER = 'SET_USER'
types.DEL_USER = 'DEL_USER'
types.SET_DEVICES = 'SET_DEVICES'
types.ADD_DEVICE = 'ADD_DEVICE'
types.DELETE_DEVICE = 'DELETE_DEVICE'
types.SET_MQTT_CONFIG = 'SET_MQTT_CONFIG'
